version: "3"

services:
  go:
    build:
      context: ./
      dockerfile: Dockerfile.prod
      target: builder
    container_name: ${GO_CONTAINER_NAME_DEV}
    command: go run main.go
    volumes:
      - ./:/go/src/app
    environment:
      - "TZ=Asia/Tokyo"
      - GOLANG_ENV=${GO_ENV_DEV}
    env_file:
      - ./mysql/.test.env
    ports:
      - ${GO_PORT_DEV}:8080
    tty: true
    stdin_open: true
    depends_on:
      - test-db
    links:
      - test-db

  test-db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: ${TEST_DB_CONTAINER_NAME_DEV}
    tty: true
    stdin_open: true
    env_file:
      - ./mysql/.test.env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake --default-time-zone=Asia/Tokyo
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - ${TEST_DB_PORT_DEV}:3306
