version: "3"

volumes:
  test_mysql_data:

services:
  go:
    build:
      context: ./
      dockerfile: Dockerfile.prod
      target: builder
    container_name: go_container_dev
    command: go run main.go
    volumes:
      - ./:/go/src/app
    environment:
      - "TZ=Asia/Tokyo"
      - GOLANG_ENV=dev
      - MYSQL_DATABASE: thesis_db
      - MYSQL_USER: anii
      - MYSQL_PASSWORD: anii
      - MYSQL_ROOT_PASSWORD: anii
      - MYSQL_CONTAINER_NAME: db_container_test
      - MYSQL_PORT: 3306
    ports:
      - 8088:8080
    tty: true
    stdin_open: true
    depends_on:
      - test-db
    links:
      - test-db

  test-db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: db_container_test
    tty: true
    stdin_open: true
    env_file:
      - ./mysql/.test.env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake --default-time-zone=Asia/Tokyo
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - test_mysql_data:/var/lib/mysql
    ports:
      - 3309:3306
