name: Ci flow for ECS

on: [push]

env:
  env_1: hashito

jobs:
  # build:
  #   name: build Dockerfile.prod
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: build Dockerfile.prod
  #       run: docker build -t myapp -f Dockerfile.prod .

  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 7

    steps:
      # - run: "repository... ${{ github.repository }}."

      - name: Checkout
        uses: actions/checkout@v3

      - name: Exec docker-compose up & test
        run: |
          docker-compose -f docker-compose.test.yml --env-file ../mysql/.env up -d --remove-orphan
          docker-compose -f docker-compose.test.yml --env-file ../mysql/.env exec go sh
          go test -v ./...
